language: node_js
node_js:
 - "10"
 - "8"
install: npm ci
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
script: 
 - npm run build
 - npm start -- &
 - npm run cypress
 - kill $(jobs -p) || true
 
